/** Integration API error codes (Platform-5.1 contract). */
const INTEGRATION_ERROR_CODE = Object.freeze({
  UNKNOWN_HOST: 'UNKNOWN_HOST',
  INACTIVE_TENANT: 'INACTIVE_TENANT',
  REGISTRY_ERROR: 'REGISTRY_ERROR',
  INVALID_TENANT: 'INVALID_TENANT',
  MISSING_API_KEY: 'MISSING_API_KEY',
  INVALID_API_KEY: 'INVALID_API_KEY',
  EXPIRED_API_KEY: 'EXPIRED_API_KEY',
  REVOKED_API_KEY: 'REVOKED_API_KEY',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  INTEGRATION_AUTH_REQUIRED: 'INTEGRATION_AUTH_REQUIRED',
  INSUFFICIENT_SCOPE: 'INSUFFICIENT_SCOPE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  IDEMPOTENCY_STORE_FAILURE: 'IDEMPOTENCY_STORE_FAILURE',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  SYNC_ALREADY_RUNNING: 'SYNC_ALREADY_RUNNING',
  LEASE_NOT_ACQUIRED: 'LEASE_NOT_ACQUIRED',
  DUPLICATE_BATCH: 'DUPLICATE_BATCH',
  CHUNK_SIZE_LIMIT_EXCEEDED: 'CHUNK_SIZE_LIMIT_EXCEEDED',
  UNSUPPORTED_PHASE: 'UNSUPPORTED_PHASE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

const INTEGRATION_ERROR_MESSAGE = Object.freeze({
  [INTEGRATION_ERROR_CODE.UNKNOWN_HOST]: 'Unknown host or tenant.',
  [INTEGRATION_ERROR_CODE.INACTIVE_TENANT]: 'Tenant is inactive.',
  [INTEGRATION_ERROR_CODE.REGISTRY_ERROR]: 'Tenant registry unavailable.',
  [INTEGRATION_ERROR_CODE.INVALID_TENANT]: 'Invalid tenant resolution.',
  [INTEGRATION_ERROR_CODE.MISSING_API_KEY]: 'API key is required.',
  [INTEGRATION_ERROR_CODE.INVALID_API_KEY]: 'Invalid API key.',
  [INTEGRATION_ERROR_CODE.EXPIRED_API_KEY]: 'API key has expired.',
  [INTEGRATION_ERROR_CODE.REVOKED_API_KEY]: 'API key has been revoked.',
  [INTEGRATION_ERROR_CODE.TENANT_MISMATCH]: 'API key does not belong to this tenant.',
  [INTEGRATION_ERROR_CODE.INTEGRATION_AUTH_REQUIRED]: 'Integration authentication is required.',
  [INTEGRATION_ERROR_CODE.INSUFFICIENT_SCOPE]: 'API key lacks required permissions.',
  [INTEGRATION_ERROR_CODE.VALIDATION_ERROR]: 'Request validation failed.',
  [INTEGRATION_ERROR_CODE.NOT_FOUND]: 'Resource not found.',
  [INTEGRATION_ERROR_CODE.CONFLICT]: 'Request conflict.',
  [INTEGRATION_ERROR_CODE.IDEMPOTENCY_KEY_REQUIRED]:
    'Idempotency-Key header is required for this write operation.',
  [INTEGRATION_ERROR_CODE.IDEMPOTENCY_CONFLICT]:
    'Idempotency-Key was reused with a different request payload.',
  [INTEGRATION_ERROR_CODE.IDEMPOTENCY_STORE_FAILURE]:
    'Failed to store or retrieve idempotency record.',
  [INTEGRATION_ERROR_CODE.INVALID_STATE_TRANSITION]:
    'Sync job state transition is not allowed.',
  [INTEGRATION_ERROR_CODE.SYNC_ALREADY_RUNNING]:
    'An active sync job already exists for this tenant.',
  [INTEGRATION_ERROR_CODE.LEASE_NOT_ACQUIRED]:
    'Could not acquire lease for sync job.',
  [INTEGRATION_ERROR_CODE.DUPLICATE_BATCH]:
    'Batch with this phase and batchIndex already exists for the job.',
  [INTEGRATION_ERROR_CODE.CHUNK_SIZE_LIMIT_EXCEEDED]:
    'Chunk exceeds maximum records per upload.',
  [INTEGRATION_ERROR_CODE.UNSUPPORTED_PHASE]:
    'Sync phase is not supported.',
  [INTEGRATION_ERROR_CODE.INTERNAL_ERROR]: 'Internal server error.',
});

const INTEGRATION_API_VERSION = 'v1';

module.exports = {
  INTEGRATION_ERROR_CODE,
  INTEGRATION_ERROR_MESSAGE,
  INTEGRATION_API_VERSION,
};
