#!/usr/bin/env node
/**
 * Provision a new marketplace client (config + storage + env template).
 * Does not create MySQL database — see project documentation for DB setup.
 *
 * Usage:
 *   node scripts/create-client.js --name "Acme Shop" --domain shop.example.com --database acme_db --storage acme
 *   npm run create-client -- --name "Acme Shop" --domain shop.example.com --database acme_db --storage acme
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.join(__dirname, '..', '..');
const REGISTRY_PATH = path.join(REPO_ROOT, 'config', 'clients.json');
const TEMPLATE_PATH = path.join(REPO_ROOT, 'config', 'clients', 'client.template.json');

function parseArgs(argv) {
  /** @type {Record<string, string>} */
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const next = argv[i + 1];
      if (!next || next.startsWith('--')) {
        throw new Error(`Missing value for --${key}`);
      }
      out[key] = next;
      i += 1;
    }
  }
  return out;
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const name = args.name;
  const domain = args.domain;
  const database = args.database;
  const storage = args.storage || slugify(domain || database || name || 'client');

  if (!name || !domain || !database) {
    console.error(
      'Usage: node scripts/create-client.js --name "Client Name" --domain shop.example.com --database client_db [--storage client]',
    );
    process.exit(1);
  }

  const id = args.id || slugify(domain.split('.')[0] || storage);

  const registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf8'));
  if (!Array.isArray(registry.clients)) {
    throw new Error('Invalid clients.json: missing clients array');
  }

  const duplicate = registry.clients.find(
    (c) => c.id === id || c.domain === domain || c.database === database,
  );
  if (duplicate) {
    console.error(
      `Client already exists (id=${duplicate.id}, domain=${duplicate.domain})`,
    );
    process.exit(1);
  }

  const record = {
    id,
    name,
    domain,
    database,
    storage,
    active: false,
  };

  registry.clients.push(record);
  fs.writeFileSync(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`, 'utf8');

  const mkdirp = require('mkdirp');
  const storageRoot = path.join(REPO_ROOT, 'storage', storage);
  for (const sub of ['products', 'logos', 'misc']) {
    mkdirp.sync(path.join(storageRoot, sub));
    const keep = path.join(storageRoot, sub, '.gitkeep');
    if (!fs.existsSync(keep)) {
      fs.writeFileSync(keep, '', 'utf8');
    }
  }

  const envTemplatePath = path.join(REPO_ROOT, 'config', 'clients', `${id}.env.example`);
  const envBody = `# ${name} — generated by create-client.js
# Add to .env (do not commit secrets)

TENANT_DEV_DOMAIN=${domain}
database=${database}

# MySQL (shared server credentials)
# host=127.0.0.1
# db_port=3306
# user=
# password=

# Optional
# MARKETPLACE_STORAGE_ROOT=${path.join(REPO_ROOT, 'storage').replace(/\\/g, '/')}
`;
  fs.writeFileSync(envTemplatePath, envBody, 'utf8');

  const clientJsonPath = path.join(REPO_ROOT, 'config', 'clients', `${id}.json`);
  fs.writeFileSync(clientJsonPath, `${JSON.stringify(record, null, 2)}\n`, 'utf8');

  console.log('Client provisioned (config + storage):');
  console.log(`  id:       ${id}`);
  console.log(`  domain:   ${domain}`);
  console.log(`  database: ${database}`);
  console.log(`  storage:  storage/${storage}/`);
  console.log(`  registry: ${REGISTRY_PATH}`);
  console.log(`  env:      ${envTemplatePath}`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. Create database manually');
  console.log('  2. Import schema / seed base_info');
  console.log('  3. Set active: true in config/clients.json');
  console.log('  4. Configure DNS / hosts and restart API');
}

main();
